application:
  subdomain: bitwarden-lite
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://bitwarden-lite:8080
services:
  bitwarden-lite:
    # ghcr.io/bitwarden/lite:2025.12.0
    # upstream: ghcr.io/bitwarden/lite:2026.7.0
    image: registry.lazycat.cloud/czyt/bitwarden/lite:2d4be134cba04723
    environment:
      - BW_DOMAIN={{.S.AppDomain }}
      - BW_DB_PROVIDER=sqlite
      - BW_DB_FILE=/etc/bitwarden/bitwarden.db
      - BW_INSTALLATION_ID={{.U.bw_installation_id}}
      - BW_INSTALLATION_KEY={{.U.bw_installation_key}}
      - globalSettings__mail__replyToEmail={{.U.reply_to_email}}
      - globalSettings__mail__smtp__host={{.U.smtp_host}}
      - globalSettings__mail__smtp__port={{.U.smtp_port}}
      - globalSettings__mail__smtp__ssl={{.U.smtp_ssl}}
      - globalSettings__mail__smtp__username={{.U.username}}
      - globalSettings__mail__smtp__password={{.U.password}}
    binds:
      - /lzcapp/var/data:/etc/bitwarden
