package: community.lazycat.app.bitwarden-lite
version: 2026.7.2
name: Bitwarden Lite
description: Bitwarden 官方精简版本服务端
min_os_version: 1.5.0
homepage: https://github.com/bitwarden/self-host
author: bitwarden
locales:
  zh:
    name: Bitwarden Lite
    description: Bitwarden 官方精简版本服务端
  en:
    name: Bitwarden Lite
    description: Bitwarden official lite version server
